version: '2'

vars:
  REPO: ynishi/json-server-docker

tasks:
  build:
    desc: build docker image
    cmds:
      - docker build -t {{.REPO}}:latest . --no-cache
      - docker build -t {{.REPO}}:${VERSION} .
  push:
    deps: [build]
    desc: push docker image
    cmds:
      - docker push {{.REPO}}:latest
      - docker push {{.REPO}}:${VERSION}
